version: '3'

services:
  scheduler:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - KATAPULT_API_KEY=${KATAPULT_API_KEY}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - ARCGIS_URL=${ARCGIS_URL}
      - ARCGIS_USERNAME=${ARCGIS_USERNAME}
      - ARCGIS_PASSWORD=${ARCGIS_PASSWORD}
      - ARCGIS_FEATURE_SERVICE=${ARCGIS_FEATURE_SERVICE}
      - ARCGIS_POLES_LAYER_ID=${ARCGIS_POLES_LAYER_ID}
      - ARCGIS_ANCHORS_LAYER_ID=${ARCGIS_ANCHORS_LAYER_ID}
      - ARCGIS_CONNECTIONS_LAYER_ID=${ARCGIS_CONNECTIONS_LAYER_ID}
    restart: unless-stopped

  app:
    build: .
    volumes:
      - .:/app
    environment:
      - KATAPULT_API_KEY=${KATAPULT_API_KEY}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - ARCGIS_URL=${ARCGIS_URL}
      - ARCGIS_USERNAME=${ARCGIS_USERNAME}
      - ARCGIS_PASSWORD=${ARCGIS_PASSWORD}
      - ARCGIS_FEATURE_SERVICE=${ARCGIS_FEATURE_SERVICE}
      - ARCGIS_POLES_LAYER_ID=${ARCGIS_POLES_LAYER_ID}
      - ARCGIS_ANCHORS_LAYER_ID=${ARCGIS_ANCHORS_LAYER_ID}
      - ARCGIS_CONNECTIONS_LAYER_ID=${ARCGIS_CONNECTIONS_LAYER_ID} 